# Generated by Django 4.1.5 on 2023-07-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
