# Generated by Django 4.1.5 on 2023-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0004_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='dob',
        ),
    ]
