# Generated by Django 4.1.5 on 2023-07-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0009_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
