# Generated by Django 4.1.5 on 2023-07-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0011_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
    ]
