# Generated by Django 4.1.5 on 2023-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0013_alter_registration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
