# Generated by Django 4.1.5 on 2023-07-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0018_remove_checkout_items_checkout_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='items',
        ),
    ]
