# Generated by Django 4.1.5 on 2023-07-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0019_remove_checkout_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_was', models.DecimalField(decimal_places=2, max_digits=8)),
                ('save', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('item_image', models.ImageField(upload_to='item/images')),
                ('item_image1', models.ImageField(blank=True, upload_to='item/images')),
                ('item_image2', models.ImageField(blank=True, upload_to='item/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
