# Generated by Django 4.1.5 on 2023-07-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0021_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
