# Generated by Django 4.1.5 on 2023-07-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_appp', '0022_rename_customer_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='username',
        ),
    ]
